-------------------------------------------------------------------------------
Test set: simhash.Main_ESTest
-------------------------------------------------------------------------------
Tests run: 9, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.649 sec <<< FAILURE! - in simhash.Main_ESTest
test1(simhash.Main_ESTest)  Time elapsed: 0.006 sec  <<< FAILURE!
java.lang.AssertionError: Exception was not thrown in java.nio.Buffer but in java.nio.HeapByteBuffer.get(HeapByteBuffer.java:139): java.lang.IndexOutOfBoundsException: 4
	at org.evosuite.runtime.EvoAssertions.assertThrownBy(EvoAssertions.java:74)
	at simhash.Main_ESTest.test1(Main_ESTest.java:46)

